import "@/styles/globals.css";

import { Inter } from "next/font/google";

import Providers from "@/components/Providers";
import { TRPCReactProvider } from "@/trpc/react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Layout from "@/components/layout/Layout";
import "antd/dist/reset.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html id="app" lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <AntdRegistry>
            <Providers>
              <Layout>{children}</Layout>
            </Providers>
          </AntdRegistry>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
